services:
  redis:
    image: redis:7.2.4-alpine
    expose:
      - 6379
    networks:
      - celery-network

  celery:
    image: lamba:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
    networks:
      - celery-network
    volumes:
      - .:/lamba

networks:
  celery-network:
    driver: bridge